name: Binary build

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      tag:
        required: false
        type: string
  push:
    branch:
      tags:
        - main

permissions: write-all


jobs:
  build-bin:
    strategy:
      matrix:
        go_arch: [amd64, arm64]
        go_version: [1.19.x]

    name: Binary Build ${{ matrix.go_arch }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Upload
        id: tag
        run: |
          if ${{ inputs.ref != '' }} ; then
            echo "call by workflow_call(e2e)"
            echo "upload=true" >> $GITHUB_OUTPUT
            echo "tag=dev" >> $GITHUB_OUTPUT
          elif ${{ inputs.tag != '' }} ; then
            echo "call by workflow_call(release push)"
            echo "upload=true" >> $GITHUB_OUTPUT
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          elif ${{ github.event_name == 'push' }} ; then
            echo "trigger by push"
            echo "upload=false" >> $GITHUB_OUTPUT
            echo "tag=main" >> $GITHUB_OUTPUT
          elif ${{ github.event_name == 'pull_request_target' }} ; then
            echo "trigger by pull_request_target"
            echo "upload=false" >> $GITHUB_OUTPUT
            echo "tag=dev" >> $GITHUB_OUTPUT
          else
            echo "unexpected event: ${{ github.event_name }}"
            exit 1
          fi

      - name: Build
        run:
          make build ARCH=${{ matrix.go_arch }} GIT_TAG=${{ steps.tag.outputs.tag }}
          if [ "${{ steps.tag.outputs.upload }}" == "true" ]; then
            cd ./.tmp/bin && tar -cvzf /home/spider-plugins-linux-${{ matrix.go_arch }}-${{ steps.tag.outputs.tag }}.tar *
          fi

      - name: Upload Binary artifact
        if: ${{ steps.tag.outputs.upload == 'true' }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: binary_files
          path: /home/spider-plugins-linux-${{ matrix.go_arch }}-${{ steps.tag.outputs.tag }}.tar
          retention-days: 1
