name: PR Label Check

# make sure the pr is labeled as wanted, case: we could generate changelog by the pr label

# Trigger the workflow on pull requests only
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

env:
  RELEASE_LABELS: "kind/bug,kind/doc,kind/feature,kind/cleanup"

jobs:
  check-label:
    name: Check pr label set
    runs-on: ubuntu-latest
    steps:
      # must set one of required label, for release note generator
      - uses: mheap/github-action-required-labels@v2.1.0
        with:
          mode: minimum
          count: 1
          labels: ${{ env.RELEASE_LABELS }}
